name: "Learning github actions"
run-name: ${{ github.actor  }} is testing out github actions
on: [push]
jobs:
  Lectus-Job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - run: echo "Hello, ${{ github.actor }}"
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install pnpm and dependencies
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: true
      - run: npm run lint
